#!/bin/sh

set -e

lb config noauto \
	--binary-images iso-hybrid \
	--checksums sha256 \
	--binary-filesystem ext4 \
	--linux-flavours amd64 \
	--architectures amd64 \
	--distribution bullseye \
	--archive-areas "main contrib non-free" \
	--updates false \
	--cache true \
	--security false \
	--debian-installer live \
	--debian-installer-distribution bullseye \
	--iso-publisher "Ether Team" \
	--iso-application "Ether Pentest" \
	--iso-volume "Ether Pentest" \
	--bootappend-live "boot=live hostname=ether splash noautomount" \
	--firmware-chroot true \
	--firmware-binary true \
	--memtest memtest86 \
	--source false \
	--backports false \
	"${@}"
