##########################################################################

name: Build CI 

on:
  push:
    paths:
      - '**.md'
    branches:
      - main
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux
      options: --privileged
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup

    steps:
      - uses: actions/checkout@v2
##########################################################################
      - name: Install Depends
        run: pacman -Sy docker docker-compose --noconfirm
        
      - name: Testing Dokcer
        run: docker-compose up 
